// Generated by SignalDeck CI — Add to Cart Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

import { test, expect } from '@playwright/test';

const atcSel = {!! json_encode($scenarioSelectors, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};
const homeSel = {!! json_encode($selectors['homepage'] ?? [], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};

// Update this URL with a real simple product path
const productUrl = '/simple-product.html';

test.describe('Add to Cart', () => {
  test('add to cart button is visible and enabled', async ({ page }) => {
    await page.goto(productUrl);
    const btn = page.locator(atcSel.add_to_cart_button);
    await expect(btn).toBeVisible();
    await expect(btn).toBeEnabled();
  });

  test('clicking add to cart shows a success message', async ({ page }) => {
    await page.goto(productUrl);
    await page.locator(atcSel.add_to_cart_button).click();
    await expect(page.locator(atcSel.success_message)).toBeVisible({ timeout: 10000 });
  });

  test('cart count increments after adding a product', async ({ page }) => {
    await page.goto('/');
    const countLocator = page.locator(homeSel.cart_count);
    const beforeText = await countLocator.textContent().catch(() => '0');
    const before = parseInt(beforeText?.trim() ?? '0') || 0;

    await page.goto(productUrl);
    await page.locator(atcSel.add_to_cart_button).click();
    await expect(page.locator(atcSel.success_message)).toBeVisible({ timeout: 10000 });

    await page.goto('/');
    const afterText = await countLocator.textContent();
    const after = parseInt(afterText?.trim() ?? '0') || 0;
    expect(after).toBeGreaterThan(before);
  });
});
