// Generated by SignalDeck CI — Cart Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

import { test, expect } from '@playwright/test';

const cartSel = {!! json_encode($scenarioSelectors, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};
const atcSel  = {!! json_encode($selectors['add_to_cart'] ?? [], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};

const productUrl = '/simple-product.html';

test.describe('Cart', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(productUrl);
    await page.locator(atcSel.add_to_cart_button).click();
    await expect(page.locator(atcSel.success_message)).toBeVisible({ timeout: 10000 });
    await page.goto('/checkout/cart');
  });

  test('displays the cart with at least one item', async ({ page }) => {
    const items = page.locator(cartSel.cart_item);
    await expect(items.first()).toBeVisible({ timeout: 10000 });
    expect(await items.count()).toBeGreaterThan(0);
  });

  test('displays a cart subtotal', async ({ page }) => {
    await expect(page.locator(cartSel.cart_subtotal)).toBeVisible();
  });

  test('checkout button is visible', async ({ page }) => {
    await expect(page.locator(cartSel.checkout_button)).toBeVisible();
  });

  test('can update item quantity', async ({ page }) => {
    await page.locator(cartSel.qty_input).first().fill('2');
    await page.locator(cartSel.update_cart).first().click();
    await expect(page.locator(cartSel.cart_subtotal)).toBeVisible({ timeout: 10000 });
  });
});
