// Generated by SignalDeck CI — Guest Checkout Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}
//
// NOTE: Use a sandbox/staging environment — these tests may place real orders.

import { test, expect } from '@playwright/test';

const checkoutSel = {!! json_encode($scenarioSelectors, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};
const atcSel      = {!! json_encode($selectors['add_to_cart'] ?? [], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};

const productUrl = '/simple-product.html';

const address = {
  email:     '{{ $testEmail }}',
  firstname: 'Test',
  lastname:  'Guest',
  street:    '1 Test Street',
  city:      'London',
  postcode:  'SW1A 1AA',
  phone:     '07700900000',
};

test.describe('Guest Checkout', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(productUrl);
    await page.locator(atcSel.add_to_cart_button).click();
    await expect(page.locator(atcSel.success_message)).toBeVisible({ timeout: 10000 });
    await page.goto('/checkout');
  });

  test('checkout page loads', async ({ page }) => {
    await expect(page).toHaveURL(/checkout/);
  });

  test('can fill in shipping details', async ({ page }) => {
    await page.locator(checkoutSel.email_input).fill(address.email);
    await page.locator(checkoutSel.firstname).fill(address.firstname);
    await page.locator(checkoutSel.lastname).fill(address.lastname);
    await page.locator(checkoutSel.street).fill(address.street);
    await page.locator(checkoutSel.city).fill(address.city);
    await page.locator(checkoutSel.postcode).fill(address.postcode);
    await page.locator(checkoutSel.phone).fill(address.phone);

    await expect(page.locator(checkoutSel.firstname)).toHaveValue(address.firstname);
  });

  // Uncomment to test full order placement in a sandbox environment
  // test('can place an order as a guest', async ({ page }) => {
  //   // ... fill address, select shipping, select payment, submit
  //   await page.locator(checkoutSel.place_order_button).click();
  //   await expect(page.locator(checkoutSel.success_heading)).toBeVisible({ timeout: 20000 });
  // });
});
