// Generated by SignalDeck CI — Search Tests
// Platform: {{ $platform }} | Base URL: {{ $baseUrl }}

import { test, expect } from '@playwright/test';

const searchSel = {!! json_encode($scenarioSelectors, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};
const homeSel   = {!! json_encode($selectors['homepage'] ?? [], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};
const productSel = {!! json_encode($selectors['product'] ?? [], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) !!};

// Update with a search term that returns results in your store
const searchTerm     = 'shirt';
const noResultsTerm  = 'xzqwerty12345notaproduct';

test.describe('Search', () => {
  test('search input is visible on the homepage', async ({ page }) => {
    await page.goto('/');
    await expect(page.locator(homeSel.search_input)).toBeVisible();
  });

  test('can submit a search and see results', async ({ page }) => {
    await page.goto('/');
    await page.locator(homeSel.search_input).fill(searchTerm);
    await page.locator(searchSel.search_button).click();
    const results = page.locator(searchSel.product_item);
    await expect(results.first()).toBeVisible({ timeout: 10000 });
    expect(await results.count()).toBeGreaterThan(0);
  });

  test('search results contain clickable product links', async ({ page }) => {
    await page.goto('/');
    await page.locator(homeSel.search_input).fill(searchTerm);
    await page.locator(searchSel.search_button).click();
    const link = page.locator(searchSel.product_link).first();
    await expect(link).toBeVisible({ timeout: 10000 });
    const href = await link.getAttribute('href');
    expect(href).toBeTruthy();
  });

  test('clicking a search result navigates to the product', async ({ page }) => {
    await page.goto('/');
    await page.locator(homeSel.search_input).fill(searchTerm);
    await page.locator(searchSel.search_button).click();
    await page.locator(searchSel.product_link).first().click();
    await expect(page.locator(productSel.product_title)).toBeVisible({ timeout: 10000 });
  });
});
